### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by BaptisteMoureaux** [itzg/docker-mc-proxy#204]
This text is written twice in the readme [here](https://github.com/itzg/docker-mc-proxy?tab=readme-ov-file#patching-existing-files) :
> JSON path based patches can be applied to one or more existing files by setting the variable PATCH_DEFINITIONS to the path of a directory that contains one or more [patch definition json files](https://github.com/itzg/mc-image-helper#patchdefinition) or a [patch set json file](https://github.com/itzg/mc-image-helper#patchset).

**Comment by itzg** [comment]
Oops, yes it is. I'll fix that up.
